### ISSUE TITLE
Ícones do UC não esta aparecendo

### ISSUE THREAD

**Issue by elidorio** [jbsolucoes/ucp#1]
![Uploading uc2015.png…]()
Olá,
Ícones do UC não esta aparecendo, estava usando a versão anterior a 10/06/15 e os ícones estavam normal.

**Comment by jbsolucoes** [comment]
Olá, Obrigado pelo report. Nos testes em desenvolvimento está funcionando. Estou verificando e em breve atualizo o repositório. Obrigado.

**Comment by jbsolucoes** [comment]
Fiz o commit da nova versão, por favor verifique.
Att.
JB

**Comment by elidorio** [comment]
Olá JB,

Este problema ainda persisti para o ícone do Zeos.

**Comment by jbsolucoes** [comment]
Fiz o ajuste, por favor verifique. Obrigado pela colaboração.

Att.
JB
