### ISSUE TITLE
SIGSEGV  on click TreeMenu (Security)

### ISSUE THREAD

**Issue by undertech2010** [jbsolucoes/ucp#11]
Hello, I have installed ucp in lazarus 1.4.4, FPC 2.6.4 SVN 49931.
It seems to works fine, but If I click on the treemenu window (user security) I have a SIGSEGV error.
This error ocours only if I click on a clean zone of TreeMenu, if I click on a checkbox to assign or not assign anything, works ok.
SIGSEGV window show me error on UserPermis_U.pas Line 516.

What can to be happening?

Thanks a lot.

Ignacio

**Comment by jbsolucoes** [comment]
Hi Ignacio, I'm fixing this problem.

Thanks for issue.

Best regards
JB

**Comment by jbsolucoes** [comment]
Fixed, please do test.

Thanks for issue.

Best regards
JB

**Comment by undertech2010** [comment]
Hello.
I am sorry, I am late for this issue.
Its Ok, test and not problem with it
.

Thanks
