### ISSUE TITLE
Trouble with User Rights

### ISSUE THREAD

**Issue by zyzmoz** [jbsolucoes/ucp#12]
I'm using UserControl1 on my main form, all the other forms have an UCControl1 setted up with actions that user can able or not, by the way, all rules doesn't work... I've tried disable the controls but not works, they stay visible and enabled to click;

Seya

**Comment by reinaldoacdc** [comment]
I have a sample project working with UserControl, if you need it to use as example, I can upload it to Git. 
It would be nice if you post some more information to see why in your project it isn't working.

**Comment by zyzmoz** [comment]
If possible I would like read your code...

**Comment by zyzmoz** [comment]
I found the trouble, I just had to delete some form creation on .lpr... I didn't pay attention on it 'cause in other projects was working fine;

**Comment by jbsolucoes** [comment]
Thanks for watch and collaboration :)
