### ISSUE TITLE
Encodig das janelas errado

### ISSUE THREAD

**Issue by fabiomattes2016** [jbsolucoes/ucp#15]
Tem que arrumar o encoding, as janelas estão com caracteres estranhos no windows

**Comment by jbsolucoes** [comment]
Vou verificar, foi feita uma correção para isso em https://github.com/jbsolucoes/ucp/commit/4d9448546391cf860440e12c8e69dd1dc970302f , verifique se está apontando o idioma Portugues

**Comment by jbsolucoes** [comment]
Resolvido
