### ISSUE TITLE
Problema de Acentuação

### ISSUE THREAD

**Issue by KreisonReis** [jbsolucoes/ucp#16]
![usersss](https://user-images.githubusercontent.com/36309250/36043840-70ed9d76-0daf-11e8-857b-b252c392e062.png)
Anexo
![sem titulo](https://user-images.githubusercontent.com/36309250/36043787-3d749c56-0daf-11e8-9c9f-8205267075f7.png)

**Comment by jbsolucoes** [comment]
Vou verificar, foi feita uma correção para isso em 4d94485 , verifique se está apontando o idioma Portugues

**Comment by jbsolucoes** [comment]
Resolvido
