### ISSUE TITLE
Erro ao compilar no Linux

### ISSUE THREAD

**Issue by andrejsilva** [jbsolucoes/ucp#18]
No Linux para compilar corretamente é necessário a seguinte alteração na unit LoginWindow_U

procedure TfrmLoginWindow.FormKeyPress(Sender: TObject; var Key: char);
begin
  if Key = #13 then
  Begin
    Key := #0;
    //Perform(WM_NEXTDLGCTL, 0, 0);
    SelectNext(ActiveControl, true, true);
  End;
end;

**Comment by jbsolucoes** [comment]
Agradecido @andrejsilva !
