### ISSUE TITLE
Problemas com Telas e Acentuações

### ISSUE THREAD

**Issue by elidorio** [jbsolucoes/ucp#2]
Olá,

Baixei a última versão e apresenta problemas
![uc3](https://cloud.githubusercontent.com/assets/2966579/8892540/ff8093fe-3332-11e5-826a-db137e9ce779.png)
![uc2](https://cloud.githubusercontent.com/assets/2966579/8892541/ff861e96-3332-11e5-87c5-0d6439aed54e.png)
![uc1](https://cloud.githubusercontent.com/assets/2966579/8892542/ff86baae-3332-11e5-9f6f-1018ce6f2538.png)

, conforme as imagens em anexo.

**Comment by jbsolucoes** [comment]
Olá, obrigado pelo report. Eu fiz a correção desse problema. Vou verificar se não foi atualizado no repositório e te informo. Estou verificando.

**Comment by elidorio** [comment]
Olá JB,

Já fez estas correções?

**Comment by jbsolucoes** [comment]
Olá Elidorio, minha versão de trabalho está corrigida, estou fazendo o commit das correções e te aviso.

Abs.

**Comment by jbsolucoes** [comment]
Fiz o commit da nova versão, por favor verifique.
Att.
JB
