### ISSUE TITLE
Personalizar Tela de Login

### ISSUE THREAD

**Issue by elidorio** [jbsolucoes/ucp#3]
Olá JB,

Gostaria de personalizar a minha tela de Login. É possível fazer isso?
Quais arquivos é preciso alterar?

Obrigado,

Edson

**Comment by jbsolucoes** [comment]
Olá, o UC possui a opção de personalizar suas telas, verifique os eventos OnCustomLoginForm (e demais).

Você pode optar também por fazer o AutoLogin (verifique na propriedade Login, basta passar as informações em runtime ativando o autologin, passando usuário e senha e em seguida chamar o UserControl.Execute.

Estou a disposição.
Att.
JB

**Comment by jbsolucoes** [comment]
Edson, adicionei uma demo customlogin, com exemplo de uso de login personalizado. Por favor verifique. Obrigado pela colaboração.

Att.
JB

**Comment by jbsolucoes** [comment]
Olá Edson, pode me confirmar se essa questão foi resolvida?

Obrigado
Abraço
JB

**Comment by elidorio** [comment]
Boa tarde,

Já foi resolvida.
