### ISSUE TITLE
UC não esta criando tela de senha inicial

### ISSUE THREAD

**Issue by elidorio** [jbsolucoes/ucp#5]
Olá JB,

A versão atual do UC não esta criando a tela da senha inicial, conforme anexo.
![ucinicial](https://github-cloud.s3.amazonaws.com/assets%2F2966579%2F10957655%2F848e266e-834d-11e5-81ce-0bbc554ab74f.png)

**Comment by jbsolucoes** [comment]
Fiz o ajuste, por favor verifique.

Att.
JB
