### ISSUE TITLE
Ajuste na tela de alterar Senha

### ISSUE THREAD

**Issue by elidorio** [jbsolucoes/ucp#6]
Olá,

Na tela de alterar Senha, precisa fazer um ajuste  no labal da tela de alterar Senha, conforme anexo.

![ajuste tela uc](https://github-cloud.s3.amazonaws.com/assets%2F2966579%2F10957691%2Fda82c264-834d-11e5-873c-801f94008e2c.png)

**Comment by jbsolucoes** [comment]
Corrigido. Obrigado pela colaboração Edson.

Att
JB
