### ISSUE TITLE
Componente UCControl  não esta funcionando

### ISSUE THREAD

**Issue by elidorio** [jbsolucoes/ucp#7]
Estou fazendo uns teste com o componente UCControl e não esta funcionando dou 2 clique neles e ele não as propriedades para adionar o controle

**Comment by jbsolucoes** [comment]
Edson, foram feitos os ajustes, agora o duplo clique no componente UCControl está funcionando. Por favor verifique. Obrigado pela colaboração.

Att.
JB

**Comment by elidorio** [comment]
Bom dia,

Agora esta funcionando, estou fazendo uns teste!
Surgiu uma dúvida, para cada form que eu quero controlar os botões eu preciso colocar um UCControl ou um UCControl e controle todos os forms?

## 

Edson

**Comment by jbsolucoes** [comment]
Bom dia, sim, pra cada form você precisa de um UCControl, ele define o grupo de controles que irão aparecer no controle de acesso.

Att.
JB
