### ISSUE TITLE
Problemas ao instalar UC em Linux 

### ISSUE THREAD

**Issue by elidorio** [jbsolucoes/ucp#9]
Olá JB,

Foi fazer a instalação do UC no meu linux Debian 64 e apresentou os problemas abaixo:

Messages, Warnings: 2
Warning: other unit files search path (aka unit path) of "pckUCDataConnector 2.32" contains "/home/lidorio/edinho/des/componentes_lazarus/ucp-master/source", which belongs to package "pckUserControlRuntime"
Warning: other unit files search path (aka unit path) of "pckUserControlRuntime 2.33" contains "/home/lidorio/edinho/des/componentes_lazarus/ucp-master/source", which belongs to package "pckUCDataConnector"
Compiling package pckUserControlRuntime 2.33: Exit code 1, Errors: 2, Warnings: 1
Warning: An inherited method is hidden by "class TUCGUID.ToString(TGuid):AnsiString;"
Error: Identifier not found "WM_NEXTDLGCTL"
Fatal: Compilation aborted
![captura de tela de 2015-11-08 22 18 40](https://cloud.githubusercontent.com/assets/2966579/11023690/5f28a954-8667-11e5-9b91-c581792e4966.png)

**Comment by jbsolucoes** [comment]
Olá Edson, estou verificando e fazendo os ajustes. Obrigado pela colaboração!

**Comment by elidorio** [comment]
Olá JB,

Esse problema do Linux vc ainda não conseguiu verificar né?
Sem querer fazer pressão, eu estava precisando rodar no linux.
Obrigado;

**Comment by elidorio** [comment]
Olá JB,

Tem alguma novidade nesse caso?

**Comment by fabiomattes2016** [comment]
Tbm tive o mesmo problema na compilação

**Comment by jbsolucoes** [comment]
Bom dia,
Atualizado com suporte a Linux, por favor verifique. Abraço.

Commit: https://github.com/jbsolucoes/ucp/commit/8c5777937bce444e74f72fb8460ad3aadcc69d27
